### ISSUE TITLE
fix ValueError: invalid literal for int() with base 10 

### ISSUE THREAD

**Issue by gabrielraya** [cics-nd/gptorch#20] opened 2020-08-29 10:47 UTC
I got this error
![ValueError](https://user-images.githubusercontent.com/15808937/87245162-7e5b7f80-c443-11ea-8855-66770f235c4c.PNG)

Apparently the fix is done by changing : 

- torch_version = [int(s) for s in torch.__version__.split(".")]

by 

- torch_version = [int(s) for s in torch.__version__.replace("+",".").split('.') if s.isdigit()]

**Comment by sdatkinson** [comment] 2020-08-29 15:11
How is torch being installed?

Also, it seems that the real underlying issue is that we're using more information than we need to in order to figure out what potri is being called by PyTorch. If all we grabbed was the major and minor version eg
```python
_torch_majorminor = [int(s) for s in torch.__version__.split(".")[:2]]
_potri = torch.cholesky_inverse if _torch_majorminor >= [1, 1] else torch.potri
```
then we wouldn't need to hack the CUDA bit on the end.
Also, this has the benefit that what potri is called doesn't depend on the patch version of PyTorch.

**Comment by sdatkinson** [comment] 2021-10-30 15:51
Should be fixed in main now. @nanxu2 @gabrielraya go ahead and try it out and let me know if it fixes the issue (I can only guess the root cause is you're installing w/ e.g. `pip install torch=1.10.0+cpu` instead of the plain `pip install torch`).

I'll put this to PyPI in a new patch version if it fixes the issue.

**Comment by nanxu2** [comment] 2021-11-01 16:23
@sdatkinson Hi Steven, It fixed the issue. The code can properly work on my desktop now. Thank you so much.

**Comment by sdatkinson** [comment] 2021-11-04 04:19
Glad to hear it :)

**Closed by sdatkinson** 2021-11-04 04:19 UTC
